apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-mar5-1
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/go-mar5-1/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/go-mar5-1-gitops
    targetRevision: main
  destination:
    namespace: go-mar5-1
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
