apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-mar5-1
  janus-idp.io/tekton: go-mar5-1
  backstage.io/kubernetes-id: go-mar5-1
  backstage.io/kubernetes-namespace: go-mar5-1 
  app.kubernetes.io/part-of: go-mar5-1
resources: 
- deployment.yaml
- route.yaml
- service.yaml
